export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
        sans:     ["Inter", "sans-serif"],
      },
      colors: {
        "surface":                   "#f4f5f7",
        "surface-bright":            "#fcfdff",
        "surface-dim":               "#c0c5cc",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#eceff2",
        "surface-container":         "#e1e6eb",
        "surface-container-high":    "#d2d9e0",
        "surface-container-highest": "#bcc6cf",
        "surface-variant":           "#c8d0d8",
        "on-surface":                "#08111b",
        "on-surface-variant":        "#3a4654",
        "inverse-surface":           "#0c1420",
        "inverse-on-surface":        "#f4f8fb",
        "primary":                   "#05080d",
        "primary-container":         "#0d1724",
        "primary-fixed":             "#1a2029",
        "primary-fixed-dim":         "#141a22",
        "on-primary":                "#f5f8fb",
        "on-primary-container":      "#ffffff",
        "on-primary-fixed":          "#ffffff",
        "on-primary-fixed-variant":  "#eef2f6",
        "secondary":                 "#5d6774",
        "secondary-container":       "#dde3e8",
        "secondary-fixed":           "#c3ccd5",
        "secondary-fixed-dim":       "#9ca8b3",
        "on-secondary":              "#ffffff",
        "on-secondary-container":    "#101820",
        "on-secondary-fixed":        "#101820",
        "tertiary":                  "#7f8b97",
        "tertiary-container":        "#e4ebf2",
        "tertiary-fixed":            "#a5b0ba",
        "tertiary-fixed-dim":        "#5f6a76",
        "on-tertiary":               "#ffffff",
        "on-tertiary-container":     "#19222b",
        "on-tertiary-fixed":         "#ffffff",
        "outline":                   "#7a8793",
        "outline-variant":           "#b7c2cd",
        "background":                "#f4f5f7",
        "on-background":             "#08111b",
        "error":                     "#ba1a1a",
        "error-container":           "#ffdad6",
        "on-error":                  "#ffffff",
        "on-error-container":        "#410002",
        "inverse-primary":           "#d8dee5",
      },
      boxShadow: {
        "ambient":    "0 20px 48px -22px rgba(8,17,27,0.22)",
        "ambient-lg": "0 32px 72px -26px rgba(8,17,27,0.28)",
        "pill":       "0 14px 38px rgba(5,8,13,0.14)",
        "drawer":     "12px 0 52px -18px rgba(8,17,27,0.28)",
      },
    },
  },
  plugins: [],
}
